name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate and build
        run: mvn --batch-mode --update-snapshots verify
      - name: Copy jars
        run: rm -rf packages/* && cp target/*.jar packages/
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: packages
      - name: Generate JavaDoc
        run: mvn javadoc:javadoc -Dshow=private
      - name: Copy documentation files
        run: |
          rm -rf docs/*
          cp -rf target/site/apidocs/. docs/
      - name: Commit packages and docs
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Mateusz Kolano'
            git config --global user.email 'MathewKnee@users.noreply.github.com'
            git add packages/
            git add docs/
            git commit -m "Automated documentation and packages update."
            git push
          fi
      
